# Generated by Django 6.1.1 on 2026-09-10 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stamps', '0002_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='stamp',
            name='keywords',
            field=models.TextField(blank=True, help_text='Comma separated keywords'),
        ),
    ]
