# Generated by Django 6.1.1 on 2026-09-10 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stamps', '0003_stamp_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='stamp',
            name='brochure_image1',
            field=models.ImageField(blank=True, null=True, upload_to='stamps/brochures/'),
        ),
        migrations.AddField(
            model_name='stamp',
            name='brochure_image2',
            field=models.ImageField(blank=True, null=True, upload_to='stamps/brochures/'),
        ),
        migrations.AddField(
            model_name='stamp',
            name='first_day_cover',
            field=models.ImageField(blank=True, null=True, upload_to='stamps/fdc/'),
        ),
    ]
