# Generated by Django 6.1.1 on 2026-09-10 07:49

import stamps.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stamps', '0004_stamp_brochure_image1_stamp_brochure_image2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stamp',
            name='brochure_image1',
            field=models.ImageField(blank=True, null=True, upload_to=stamps.models.brochure_upload_path),
        ),
        migrations.AlterField(
            model_name='stamp',
            name='brochure_image2',
            field=models.ImageField(blank=True, null=True, upload_to=stamps.models.brochure_upload_path),
        ),
        migrations.AlterField(
            model_name='stamp',
            name='first_day_cover',
            field=models.ImageField(blank=True, null=True, upload_to=stamps.models.fdc_upload_path),
        ),
        migrations.AlterField(
            model_name='stamp',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=stamps.models.stamp_upload_path),
        ),
    ]
